---
title: 'June 7'
date: '2023-06-07'
categories: ['Week 1', 'Events']
description: 'Highlights from the 16th Annual Student-Organized Bioinformatics Symposium.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

Today was spent at the 16th Annual BU Bioinformatics Student-Organized Symposium. I found the entire symposium very interesting and filled up five pages of my notebook with concepts, techniques, and papers mentioned in the presentations that I wanted to save to look up on my own later. Here are some examples of things I recorded that were novel to me or that particularly caught my interest:

*   The phyllosphere
*   Flux Balance Analysis
*   MacArthur's consumer-resource model
*   Genomic epidemiology

My favorite part of the symposium was Dr. Alan Pacheco's presentation on "Mapping Interaction Networks in Plant Microbiomes", although I also enjoyed PhD candidate Helen Scott's lightning talk on "Charting Carbon Use Efficiency in Ocean Microbiomes".

Cool papers mentioned or cited at the conference include:

*    Microbiology of the phyllosphere ([Lindow and Brandl, 2003](https://doi.org/10.1128%2FAEM.69.4.1875-1883.2003))
*    Mapping phyllosphere microbiota interactions in planta to establish genotype-phenotype relationships ([Schäfer et al., 2022](https://doi.org/10.1038/s41564-022-01132-w))
*    A protocol for generating a high-quality genome-scale metabolic reconstruction ([Thiele and Palsson, 2010](https://doi.org/10.1038%2Fnprot.2009.203))
*    What is flux balance analysis? ([Orth et al., 2010](https://doi.org/10.1038%2Fnbt.1614))
*    Fast automated reconstruction of genome-scale metabolic models for microbial species and communities ([Machado et al., 2018](https://doi.org/10.1093/nar/gky537))