project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Ruby's Lab Notebook - Summer 2023"
  sidebar:
    style: "docked"
    search: false
    contents:
    - section: "Resources"
      contents:
       - Resources/Papers.qmd
       - Resources/EDM.qmd
    - section: "Project Updates"
      contents:
        - posts/Week1.qmd
        - posts/Week2words.qmd
        - posts/Week2R.qmd

format:
  html:
    theme: flatly
    css: styles.css

toc: true
toc-depth: 3
# Enable banner style title blocks
title-block-banner: false

page-layout: article

