project:
  type: website

website:
  title: "Ruby's Lab Notebook - Summer 2023"
  navbar:
    right:
      - text: Project Updates
        href: blog.qmd 
      - icon: github
        href: https://github.com/rmk118 
      - icon: twitter
        href: https://twitter.com/rmk118
format:
  html:
    theme: flatly
    css: styles.css



