project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Ruby's Lab Notebook - Summer 2023"
  # navbar:
    # right:
    #   - text: Project Updates
    #     href: blog.qmd 
    #   - icon: github
    #     href: https://github.com/rmk118/lab_notebook
    
  sidebar:
    style: "docked"
    search: false
    contents:
    - section: "Resources"
      contents:
       - Resources/Papers.qmd
       - Resources/EDM.qmd
    - section: "Project Updates"
      contents:
        - posts/Jun8.qmd
        - posts/Jun7/Jun7.qmd
        - posts/Jun6/Jun6.qmd

format:
  html:
    theme: flatly
    css: styles.css

toc: true


