project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Ruby's Lab Notebook - Summer 2023"
  sidebar:
    style: "docked"
    search: false
    contents:
    - section: "Resources"
      contents:
       - Resources/Papers.qmd
       - Resources/EDM.qmd
    - section: "Project Updates"
      contents:
        - posts/Jun13_14.qmd
        - posts/Jun12.qmd
        - posts/Jun9.qmd
        - posts/Jun8.qmd
        - posts/Jun7/Jun7.qmd
        - posts/Jun6/Jun6.qmd

format:
  html:
    theme: flatly
    css: styles.css

toc: true
toc-depth: 3
# Enable banner style title blocks
title-block-banner: false

page-layout: article

