---
title: 'Intro to EDM'
date: '2023-07-06'
categories: ['Resources']
description: 'An overview of Empirical Dynamic Modeling (EDM) as I understand it. The goal is to perform somewhat of a literature review and solidify my understanding of EDM and its applications by describing the concepts in my own words, or at least compile language from the various sources that have been most helpful in building my intuition around EDM.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

# Dynamical systems

A dynamical system is a system whose state is uniquely specified by a set of variables (state variables) and whose behavior is described by predefined rules [@sayama2015]. The dynamical system evolves over time in the state space, which is the set of all possible values of the state variables. If a state space is continuous (i.e., the state variables are not restricted to discrete values) and finite-dimensional, the number of state variables defines the dimension of the dynamical system [@nykamp].

If a dynamical system is deterministic, future states of the system can be predicted from the past behavior of the system, even if the trajectories appear chaotic [@sugihara1990]. In a nonlinear system, interactions between variables are state-dependent: for example, the correlation between fish and zooplankton populations in the Baltic Sea changes sign depending on planktivore abundance, with two different ecosystem configurations (top-down vs. bottom-up forcing) on either side of a planktivore threshold [@casini2009].

<!-- The logistic equation $$ \frac{dN}{dt}=rN(1-\frac{N}{K}) $$ is nonlinear because the change in population of species N is not proportional to the current abundance of N: if N is half of the carrying capacity K, the population of N will be growing much faster than if N is very close to K. -->

Empirical dynamic modeling (EDM) uses time series data to analyze and forecast nonlinear systems, which are extremely common in the natural world [@deyle2016]. Ecologists classically model species interactions using a community matrix, a matrix of the partial derivatives (the Jacobian) of the system evaluated at equilibrium. The sign and magnitude of the coefficients in the matrix represent the direction and intensity, respectively, of the impact of a change in population of one species on the population of another. However, as with the Baltic Sea fish example, having a single matrix of coefficients does not suffice to describe a complex nonlinear system because the interaction between species can vary with the state of the ecosystem [@deyle2016]. Methods based on linear regression to analyze nonlinear ecological systems assume separability of variablespresents a host of issues, including the inability to distinguish interactions between species from the effect of a shared driving variable like temperature (see the [Moran Effect](https://en.wikipedia.org/wiki/Moran%27s_theorem)).

> In EDM, the state of a dynamical system is a specific location in a multivariate coordinate space, or state space, whose coordinate axes are causally coupled ecosystem variables such as species abundance, temperature, resources, etc. The state of the system changes in time according to the rules/equations that describe the system dynamics, and this in turn traces out a trajectory. The collection of these time-series trajectories forms a geometric object called an attractor manifold, which describes empirically how variables relate to each other in time. [@deyle2016]

Motion on the attractor manifold can be projected onto a coordinate axis, forming a time series. On the other hand, we can use time series data to reconstruct the dynamics of the system in multidimensional state space, called attractor reconstruction [@chang2017]. In the real world, we often lack the necessary data (e.g., time series for cod, phytoplankton, and zooplankton) to reconstruct the dynamics of a system, and we likely do not even know all of the variables that dictate the state of the system. Using Takens' theorem, we can use time-delay embedding to reconstruct a "shadow manifold" that preserves the essential dynamics of the original system.

# Simplex projection and s-mapping

<!-- # Spatial EDM -->

<!-- Spatial data can be incorporated into EDM in a variety of ways. -->
