---
title: 'June 6'
date: '2023-06-06'
categories: ['Intro']
description: 'My first day on the job! Here a brief summary of some of the articles I read today, where my project might be going, and a description of what I learned about Git, GitHub, R Markdown, and Quarto.'

execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# Papers
I spent much of today reading the papers that Dr. Deyle provided related to EDM and quantitative fisheries. The EDM papers included applications of the approach to specific case studies, as well as the mathematical background. For example, [@sugihara_detecting_2012] is the foundational paper describing the use of EDM to detect causality through convergent cross-mapping (CCM).

I also familiarized myself with recent modeling studies related to the Atlantic sea scallop fishery. The economic value of the scallop fishery and the availability of high-quality time series data make scallops a good choice for meaningful applied data science. There have been various models created to estimate biomass (stock assessments), estimate natural mortality, and to develop an Integrated Assessment Model to inform fishery management under changing oceanographic conditions. However, these models depend on assumptions (especially about stock-recruitment relationships) that may not be justified. EDM could potentially provide new insights into the factors that impact scallop abundance without needing to make such assumption.

There are also many interesting spatial dynamics to consider, particularly related to the rotational management plans implemented by the New England Fishery Management Council. Another potential area of investigation relates to new research by Pousse et al., [-@pousse_juvenile_2023] indicating that ocean acidification depresses the growth of juvenile Atlantic sea scallops. This research highlights the need for accurate forecasting of scallop populations under projected acidification conditions in order to ensure the continued prosperity of the fishery.

# Building this notebook

## Git and GitHub
Unfortunately, I had to spend several hours today wrangling with Git and GitHub in order to create the new repository for this notebook and successfully connect it to GitHub. The main issues were related to inconsistent authentication protocols (HTTPS vs. ssh) between my GitHub account, GitHub CLI, and local repo. Eventually, I resolved the issues and successfully link the local and remote directories and deploy this notebook as a GitHub pages site associated with the repository.

## Quarto and Markdown
It has been several years since I last worked in Markdown, and I reviewed the basic syntax: headers, italics, bullet points, inserting links, etc. My previous experience using Markdown syntax was in R Markdown, but for this lab notebook I decided to learn Quarto. [Quarto](https://quarto.org/) is an "open-source scientific and technical publishing system" that is used by academics to create static and dynamic documents, personal websites, CVs, books, and other media. Called the next generation of R Markdown, knowing how to use Quarto will be a valuable skill for this REU project as well as future research endeavors.

# Goals/Future Work
1. Finish reading the all of the quantitative fisheries papers that Dr. Deyle provided
2. Create a blog page (blog = lab notebook website) to collect and organize my list of relevant papers
3. EDM
    a. Create an "Intro to EDM" blog page where I can summarize my understanding of EDM and associated analytical techniques. I am not sure that my grasp of the theory behind EDM is solid enough to accurately apply it to complex systems or to explore new conceptual areas, and I think that writing such a page (much like teaching a concept to someone else) will help me identify and resolve gaps in my understanding.
    b. Solidify my understanding of the different ways that EDM can incorporate spatial data. I plan to re-read some of the key spatial EDM papers to review the theory and the methods they used, as during my initial read I mostly focused on the introduction, results, and discussion/conclusions. I primarily want to feel more confident in my ability to determine which approach(es) would be most suitable for a given data set.
4. Begin looking at the scallop data


# References