---
title: 'Intro to EDM'
date-modified: '2023-06-12'
categories: ['Resources']
description: 'An overview of Empirical Dynamic Modeling (EDM). The goal is to perform somewhat of a literature review and solidify my understanding of EDM and its applications by describing the concepts in my own words, or at least compile language from the various sources that have been most helpful in building my intuition around EDM.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: ../references.bib
---

# Introduction

A dynamical system is a system whose state is uniquely specified by a set of variables (state variables) and whose behavior is described by predefined rules [@sayama2015]. The dynamical system evolves over time in the state space, which is the set of all possible values of the state variables. If a state space is continuous (i.e., the state variables are not restricted to discrete values) and finite-dimensional, the number of state variables defines the dimension of the dynamical system.

If a dynamical system is deterministic, future states of the system can be predicted from the past behavior of the system, even if the trajectories appear chaotic [@sugihara1990]. In a nonlinear system, interactions between variables are state-dependent: for example, the correlation between fish and zooplankton populations in the Baltic Sea changes sign depending on planktivore abundance, with two different ecosystem configurations (top-down vs. bottom-up forcing) on either side of a planktivore threshold [@casini2009].

<!-- The logistic equation $$ \frac{dN}{dt}=rN(1-\frac{N}{K}) $$ is nonlinear because the change in population of species N is not proportional to the current abundance of N: if N is half of the carrying capacity K, the population of N will be growing much faster than if N is very close to K. -->

Empirical dynamic modeling (EDM) uses time series data to analyze and forecast nonlinear systems, which are extremely common in the natural world [@deyle2016]. Ecologists classically model species interactions using a community matrix, a matrix of the partial derivatives (the Jacobian) of the system evaluated at equilibrium. The sign and magnitude of the coefficients in the matrix represent the direction and intensity, respectively, of the impact of a change in population of one species on the population of another. However, as with the Baltic Sea fish example, having a single matrix of coefficients does not suffice to describe a complex nonlinear system because the interaction between species can vary with the state of the ecosystem [@deyle2016]. Methods based on linear regression to analyze nonlinear ecological systems, while extremely valuable, have many weaknesses, including the inability to distinguish interactions between species from the effect of a shared driving variable like temperature (see the [Moran Effect](https://en.wikipedia.org/wiki/Moran%27s_theorem)).

> In EDM, the state of a dynamical system is a specific location in a multivariate coordinate space, or state space, whose coordinate axes are causally coupled ecosystem variables such as species abundance, temperature, resources, etc. The state of the system changes in time according to the rules/equations that describe the system dynamics, and this in turn traces out a trajectory. The collection of these time-series trajectories forms a geometric object called an attractor manifold, which describes empirically how variables relate to each other in time. [@deyle2016]

Motion on the attractor manifold can be projected onto a coordinate axis, forming a time series. On the other hand, we can use time series data to reconstruct the dynamics of the system in multidimensional state space, called attractor reconstruction [@chang2017]. In the real world, we often lack the necessary data (e.g., time series for cod, phytoplankton, and zooplankton) to reconstruct the dynamics of a system, and we likely do not even know all of the variables that dictate the state of the system. Using Takens' theorem, we can use time-delay embedding to reconstruct a "shadow manifold" that preserves the essential dynamics of the original system.

[Introduction to Empirical Dynamic Modeling](https://youtu.be/fevurdpiRYg) (YouTube video)

[Constructing Empirical Dynamic Models: Takens'Theorem](https://youtu.be/QQwtrWBwxQg) (YouTube video)

## Simplex Projection

Simplex projection is a non-parametric analysis in state space used to determine the optimal embedding dimension, $E$, of a system. This is important for future EDM techniques and can offer insight into the dimensionality (and complexity) of a given system. Papers that provide helpful and more technically rigorous descriptions of simplex projection include @ye2015, @chang2017, @sugihara1990, and the [vignette](https://cran.r-project.org/web/packages/rEDM/vignettes/rEDM-tutorial.pdf) for the R package rEDM, which also describes how to perform the analysis in R. Roughly, simplex projection is done as follows:

1.  Choose an embedding dimension, $E$
2.  Use the $E+1$ nearest neighbors of the target point in $E$-dimensional space to enclose the predictee in a minimal polygon (simplex)
3.  Use the future position of the simplex to predict the future position of the predictee
    -   Take the weighted average of the forward evolutions of the neighboring points (the average scaled by Euclidean distance of the nearest neighbor to the predictee)
4.  Evaluate the predictive skill of the simplex projection, such as by computing the correlation coefficient $\rho$ between the forecasted and observed results.
5.  Repeat the process with different values of $E$ to determine which $E$ results in the highest predictive skill, indicating the optimal embedding dimension

\*\*NOTES \*\*

-   $E$ is *not* necessarily the same as the true dimension of the system, $D$, or the number of variables being analyzed (e.g., number of species in a trophic web), but it is bounded such that $E<2D+1$
-   It is sometimes helpful to take the first differences in a target variable to distinguish meaningful prediction ability arising from the system dynamics from the statistical prediction resulting from autocorrelation. For example, @deyle2018 used $ΔLPUE(t) = LPUE(t + 1) − LPUE(t)$ rather than simply $LPUE(t)$.

## S-Map Analysis

S-map analysis can be used to distinguish nonlinear dynamical systems from linear stochastic systems and identify the degree of state-dependency of a system [@sugihara1994].S-mapping is a forecasting method that uses locally weighted multivariate linear regressions calculated as the system moves along its attractor. Rather than using only nearby points, S-maps uses the entire library of points on the attractor, where points are given an exponentially decaying weight based on their distance from the target point.

Helpful explanations of how S-mapping works can be found in the Methods sections of [@glaser2011],[@deyle2016] and [@deyle2018], as well as in [@chang2017].

> S-map analysis is a locally weighted linear regression performed under the state space associated with a weighting function in the form of an exponential decay kernel, $w(d) = e^{(−θ d/\bar{d})}$. Here, $d$ is the distance between the predictee and each library point, and $\bar{d}$ is the mean distance of all paired library points. The parameter θ controls the degree of state dependency. If θ = 0, all library points have the same weight regardless of the local state of the predictee; mathematically, this model reduces to a linear autoregressive model. In contrast, if θ \> 0, the forecast given by the S-map depends on the local state of the predictee, and thus produces locally different fittings. Therefore, by comparing the performance of equivalent linear (θ = 0) and nonlinear (θ \> 0) S-map models, one can distinguish nonlinear dynamical systems from linear stochastic systems. [@chang2017]

We can quantify the state-dependency of the system by finding the improvement in prediction skill of the nonlinear model compared to a linear model, $Δ\rho=\rho_\theta-\rho_{(\theta=0)}$. The statistical significance of S-map results can be analyzed by generating a randomized version of the time series that maintains the fundamental statistical properties of the real data set (like autocorrelation), but is otherwise completely random. Performing S-map analysis on a large sample of such randomly-generated series will generate a null distribution of the S-map predictability $\rho$ and $Δ\rho$. Thus, we can find the probability of obtaining the $\rho$ and $Δ\rho$ values from the real data if the underlying nonlinear dynamics were not present.

## Convergent Cross-Mapping (CCM)

[State Space Reconstruction: Convergent Cross Mapping](https://youtu.be/NrFdIz-D2yM) (YouTube video)

CCM can detect causal linkages between time series and distinguish such causality from correlation arising from a shared environmental driver. [@sugihara2012] provides a comprehensive description of how CCM works, with general explanations also available in [@chang2017], [@ye2015a],[@deyle2013], and [@deyle2018], among others.

In essence, CCM measures the extent to which the historical record of $Y$'s values (the shadow manifold $M_Y$ built from $Y$ and the appropriate number of time lags) can be used to predict states of $X$. If $X$ causes $Y$, information about the state of $X$ can be recovered from $M_Y$ and having a more detailed $M_Y$ (bigger library size = a denser manifold) increases the prediction skill of $X$. Therefore, significant convergence when using $M_Y$ to predict $X$ (i.e., $Y$ crossmap $X$) indicates causality in the reverse direction, $X\Rightarrow Y$. For a stochastic forcing variable $X$, the current state of $Y$ cannot be inferred from values of $X$, so a manifold reconstructed from lags of $X$ will not reliably estimate $Y$; i.e., $X$ crossmap $Y$ will fail to converge.

Here is a collection of papers that have used CCM to identify causality in complex ecosystems. (Note that papers incorporating spatial data into CCM are in the following section.)

| Author, year  | Title                                                                          | Notes                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|----------------|---------------------|-----------------------------------|
| @sugihara2012 | Detecting Causality in Complex Ecosystems                                      | The must-read paper describing CCM! Describes different possibilities: bidirectional causality via functional coupling, unidirectional causality, and more complex models. Supplementary material is also helpful, esp. Box S1 (pg. 37). Examples included: (1) Bidirectional coupling b/w Didinium (predator) and Paramecium (prey), and (2) Anchovy, sardine, and SST: species aren't coupled to each other, but weakly forced by same envi. driver |
| @deyle2013    | Predicting climate effects on Pacific sardine                                  | Builds off @sugihara2012, which established that sardine pop. is state-dependent and temp does impact sardines. Uses multivariate EDM first on toy Ricker model, then on real data to predict the effect of changes in SST on sardines, explore possible temp scenarios                                                                                                                                                                               |
| @ye2015a      | Distinguishing time-delayed causal interactions using convergent cross mapping | Overcoming "generalized synchrony": the problem that CCM can't distinguish b/w very strong unidirectional forcing and bidirectional causality bc strong unidirectional forcing by X on Y can make the system (X and Y) collapse to just the dynamics of X, so CCM is observed in both directions. Considering different time lags for CCM uncovers asynchrony when there is a detectable lag b/w cause and effect. See Fig. 1. Cool!                  |
| @mcgowan2017  | Predicting coastal algal blooms in southern California                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| @chang2017    | Empirical dynamic modeling for beginners                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| @deyle2018    | Ecosystem-based forecasts of recruitment in two menhaden species               |                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|               |                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

# Spatial EDM

There are several different approaches to incorporating spatial dynamics into EDM.

Here is a collection of papers that have analyzed the spatio-temporal dynamics of a natural system using EDM:

| Author, year      | Title                                                                                                                                     | Notes                                                                                                                                                                                                                                                                                                                                                                                            |
|-----------------|-----------------|---------------------------------------|
| @hsieh2008        | Extending Nonlinear Analysis to Short Ecological Time Series                                                                              | Combines ecologically similar multispecies time series into one longer (**composite**) time series. Offers 3 tests to ensure accurate results and tests method with 23 Pacific coastal fish species. (dewdrop)                                                                                                                                                                                   |
| @glaser2011       | Detecting and forecasting complex nonlinear dynamics in spatially structured catch-per-unit-effort time series for North Pacific albacore | Uses spatially disaggregated data to increase info density, create **composite** time series, produce annual CPUE forecast at 2 different spatial scales. Figs. 4, 5 are a cool way of explaining simplex projection and S-maps. Standardizing CPUE removed signature of nonlinearity. Use of target-composite to forecast individual cells produced better forecasts than single cell analysis. |
| @clark2015        | Spatial convergent cross mapping to detect causal relationships from short time series                                                    |                                                                                                                                                                                                                                                                                                                                                                                                  |
| @mcnamara2019     | Insights into coral reef benthic dynamics from nonlinear spatial forecasting                                                              |                                                                                                                                                                                                                                                                                                                                                                                                  |
| @brito-millán2019 | Influence of aggregation on benthic coral reef spatio-temporal dynamics                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                  |
| @johnson2021      | Leveraging spatial information to forecast nonlinear ecological dynamics                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                  |
|                   |                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                  |

# Other EDM papers

| Author, year  | Title                                                                                                                              | Notes                                                                                                                                                                                                                                                                                                                                                                                                                       |
|----------------|----------------|---------------------------------------|
| @dixon1999    | Episodic Fluctuations in Larval Supply                                                                                             | Concluded variation in recruitment arises from nonlinear response of larval reef fish to key physical forcing variables. Used S-maps to show predictability of egg production and recruitment didn't improve with increasing nonlinearity, but larval supply did. Modeled larval supply based on 3 biological drivers, concluded fluctuations result from both deterministic (lunar) and stochastic (wind stress) variables |
| @hsieh2005    | Distinguishing random environmental fluctuations from ecological catastrophes for the North Pacific Ocean                          | Physical indices examined were linear stochastic, in contrast to the biological time series, which could be modeled as low-dimensional nonlinear processes. Concludes: ecological ocean dynamics can be characterized as nonlinear amplification (by biological processes) of stochastic physical forcing.                                                                                                                  |
| @royer2006    | Recurrent and density-dependent patterns in long-term fluctuations of Atlantic bluefin tuna trap catches                           | Helpful explanation of generating surrogates with white or red noise as a null hypotheses to test for determinism. Uses recurrence analysis rather than EDM: similar (uses lagged coordinate embedding) but uses fitting instead of prediction/forecasting and provides qual. rather than quant. info about nonlinearity                                                                                                    |
| @anderson2008 | Why fishing magnifies fluctuations in fish abundance                                                                               | Tests three different hypothesis about relationship b/w fishing and stock variability, uses S-maps to find that age-truncated pops have increasingly unstable pop dynamics bc of changing demographic parameters, not bc of variable fishing pressure or more closely tracking environmental variation                                                                                                                      |
| @ye2015       | Equation-free mechanistic ecosystem forecasting using empirical dynamic modeling                                                   | Compares EDM spawner-recruit forecast model for sockeye salmon to Ricker model and incoroporates environment: compares extended Ricker to multivariate EDM. EDM \> Ricker, and including envi variables improves forecasting. 9 different salmon stocks, modeled separately. Includes R scripts                                                                                                                             |
| @tsonis2015   | Dynamical evidence for causality between galactic cosmic rays and interannual variation in global temperature                      | Uses S-maps and CCM to show that cosmic rays are coupled to global temp, but aren't measurably contributing to gloabl warming. Also see @ye2015b                                                                                                                                                                                                                                                                            |
| @deyle2016a   | Global environmental drivers of influenza                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                             |
| @li2021       | Beyond linearity, stability, and equilibrium: The edm package for empirical dynamic modeling and convergent cross-mapping in Stata |                                                                                                                                                                                                                                                                                                                                                                                                                             |
| @munch2023    | Recent developments in empirical dynamic modelling                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                             |

# References
