---
title: 'Relevant Papers'
date-modified: '2023-06-16'
categories: ['Resources']
description: 'A list of non-EDM scientific literature that is clearly or potentially related to my project. Papers related to EDM can be found on the Intro to EDM page.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: ../references.bib
---

# Quantitative Fisheries (from Dr. Deyle)

| Author, year   | Title                                                                                                                                        |
|----------------|----------------------------------------------------------------------------------------------------------------------------------------------|
| @overholtz2009 | A simulation model to explore the response of the Gulf of Maine food web to large-scale environmental and ecological changes                 |
| @link2009      | Response of balanced network models to large-scale perturbation: Implications for evaluating the role of small pelagics in the Gulf of Maine |
| @ross2021      | Projecting regions of North Atlantic right whale, *Eubalaena glacialis*, habitat suitability in the Gulfof Maine for the year 2050           |

# Food webs & ecosystem-based management

| Author, year | Title                                                                                                 |
|--------------|-------------------------------------------------------------------------------------------------------|
| @link2002    | Does food web theory work for marine ecosystems?                                                      |
| @tam2017     | Towards ecosystem-based management: identifying operational food-web indicators for marine ecosystems |

# Atlantic sea scallops

*See the Scallop Resources page for more scallop-related literature*

| Author, year    | Title                                                                                                                                                      |
|-----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| @bethoney2016   | Implications of extremely high recruitment events into the US sea scallop fishery                                                                          |
| @cooley2015     | An Integrated Assessment Model for Helping the United States Sea Scallop (Placopecten magellanicus) Fishery Plan Ahead for Ocean Acidification and Warming |
| @hart2003       | Yield- and biomass-per-recruit analysis for rotational fisheries, with an application to the Atlantic sea scallop                                          |
| @hart2006       | Effects of sea stars and crabs on sea scallop Placopecten magellanicus recruitment in the Mid-Atlantic Bight (USA)                                         |
| @hart2022       | Estimating natural mortality for Atlantic Sea scallops (Placopecten magellenicus) using a size-based stock assessment model                                |
| @hart2013       | To split or not to split: Assessment of Georges Bank sea scallops in the presence of marine protected areas                                                |
| @pousse2023     | Juvenile Atlantic sea scallop, Placopecten magellanicus, energetic response to increased carbon dioxide and temperature changes                            |
| @rheuban2018    | Projected impacts of future climate change, ocean acidification, and management on the US Atlantic sea scallop (Placopecten magellanicus) fishery          |
| @shank2012      | Post-settlement predation by sea stars and crabs on the sea scallop in the Mid-Atlantic Bight                                                              |
| @stokesbury2012 | Stock Definition and Recruitment: Implications for the U.S. Sea Scallop (Placopecten magellanicus) Fishery from 2003 to 2011                               |
| @truesdell2016  | Effects of spatial heterogeneity in growth and fishing effort on yield-per-recruit models: an application to the US Atlantic sea scallop fishery           |
| @zang2023       | Effects of warming and fishing on Atlantic sea scallop (Placopecten magellanicus) size structure in the Mid-Atlantic rotationally closed areas             |

# Other

| Author, year | Title                                                                                  | Notes                                                                                                                                                                                    |
|--------------|----------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| @maunder2004 | Standardizing catch and effort data: a review of recent approaches                     | Good background on CPUE. Includes intro to catch data standardization, dealing with zeros and interactions, and selecting explanatory variables                                          |
| @hsieh2008a  | Spatial analysis shows that fishing enhances the climatic sensitivity of marine fishes | Analyzed spatial area of occupancy and index of spatial heterogeneity, and changes in distribution from cold to warm period. Used linear regression and a variety of nonparametric tests |

| Author, year     | Title                                                                                    |
|------------------|------------------------------------------------------------------------------------------|
| @hamel2023       | Natural mortality: Theory, estimation and application in fishery stock assessment models |
| @kenchington2014 | Natural mortality estimators for information-limited fisheries                           |
