---
title: 'Scallop Links'
date-modified: '2023-06-16'
categories: ['Resources']
description: 'A list of key scientific literature related to North Atlantic sea scallops, with an emphasis on the use of NMFS survey data for modeling purposes.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: ../references.bib
editor: 
  markdown: 
    wrap: 72
---

### General

| Author, year        | Title                                                                                                                                                                                                                                                                                                                           | Notes                                                                                                                                |
|--------------|-------------------------------------------|----------------|
| Hart and Rago, 2006 | [Long-Term Dynamics of U.S. Atlantic Sea Scallop Placopecten magellanicus Populations](https://afspubs.onlinelibrary.wiley.com/doi/full/10.1577/M04-116.1)                                                                                                                                                                      | Excellent historical overview                                                                                                        |
| Hart et al., 2013   | [To split or not to split: Assessment of Georges Bank sea scallops in the presence of marine protected areas](https://www.sciencedirect.com/science/article/pii/S0165783612003396#bib0040)                                                                                                                                      | Ran CASA model (aggregate and split by area) on real data and SAMS simulated data                                                    |
| Lee et al., 2019    | [Resource Abundance, Fisheries Management, and Fishing Ports: The U.S. Atlantic Sea Scallop Fishery](https://www.cambridge.org/core/journals/agricultural-and-resource-economics-review/article/resource-abundance-fisheries-management-and-fishing-ports-the-us-atlantic-sea-scallop-fishery/C123D92B0821542C2185D6A2F42EB62F) | Uses inverse-distance weighted available biomass index                                                                               |
| Zang et al., 2022   | [Modeling Atlantic sea scallop (Placopecten magellanicus) scope for growth on the Northeast U.S. Shelf](https://onlinelibrary.wiley.com/doi/full/10.1111/fog.12577)                                                                                                                                                             | MATLAB scope for growth model [available here](http://ulysse2.whoi.edu:8080/thredds/catalog/data/zzang/Project_Scallop/catalog.html) |

### Recruitment

-   [Yield- and biomass-per-recruit analysis for rotational fisheries,
    with an application to the Atlantic sea
    scallop](https://www.researchgate.net/publication/279700466_Yield-_and_biomass-per-recruit_analysis_for_rotational_fisheries_with_an_application_to_the_Atlantic_sea_scallop_Placopecten_magellanicus)
    (Hart, 2003)
-   [Effects of spatial heterogeneity in growth and fishing effort on
    yield-per-recruit models: An application to the US Atlantic sea
    scallop fishery](http://dx.doi.org/10.1093/icesjms/fsv238)
    (Truesdell, 2015)
-   [Stock Definition and Recruitment: Implications for the U.S. Sea
    Scallop (Placopecten magellanicus) Fishery from 2003 to
    2011](https://www.tandfonline.com/doi/abs/10.1080/10641262.2012.695816?journalCode=brfs20)
    (Stokesbury, 2012)
-   [Implications of extremely high recruitment events into the US sea
    scallop
    fishery](https://www.int-res.com/abstracts/meps/v547/p137-147/)
    (Bethoney, Asci, and Stokesbury, 2016)
-   [Implications of extremely high recruitment: crowding and reduced
    growth within spatial
    closures](https://www.int-res.com/abstracts/meps/v611/p157-165/)
    (Bethoney and Stokesbury, 2019)

### Distribution, population assessment, habitat, camera surveys

-   [An Assessment of Juvenile and Adult Sea Scallop, Placopecten
    magellanicus, Distribution in the Northwest Atlantic using
    High-Resolution Still Imagery](https://doi.org/10.2983/035.030.0301)
    (Carey and Stokesbury, 2011)
-   [Sea scallops exhibit strong local spatiotemporal structure
    associated with seabed stability and high
    flows](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.2133)
    (Harris, Adams, and Stokesbury, 2018)
-   [Spatial scaling of juvenile--adult associations in northwest
    Atlantic sea scallop Placopecten magellanicus
    populations](https://www.int-res.com/abstracts/meps/v493/p185-194/)
    (Carey, Wahle, and Stokesbury, 2013)
-   [Fertilization success in scallop aggregations: reconciling model
    predictions and field measurements of density
    effects](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.2359)
    (Bayer et al., 2018)
-   [An ensemble high-resolution projection of changes in the future
    habitat of American lobster and sea scallop in the Northeast US
    continental
    shelf](https://onlinelibrary.wiley.com/doi/full/10.1111/ddi.13069)
    (Tanaka et al., 2020)
-   [How many sea scallops are there and why does it
    matter?](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/fee.2244)
    (Stokesbury and Bethoney, 2020)
-   [Measurement errors in body size of sea scallops (Placopecten
    magellanicus) and their effect on stock assessment
    models](https://aquadocs.org/handle/1834/25410) (Jacobson et al.,
    2010) 
-   [Estimation of Sea Scallop Abundance in Closed Areas of Georges
    Bank,
    USA](https://doi.org/10.1577/1548-8659(2002)131%3C1081:EOSSAI%3E2.0.CO;2)
    (Stokesbury, 2002)
-   [Spatial distribution of the giant scallop Placopecten magellanicus
    in unharvested beds in the Baie des Chaleurs,
    Quebec](https://www.int-res.com/articles/meps/96/m096p159.pdf)
    (Stokesbury and Himmelman, 1993)
-   [Biological and physical variables associated with aggregations of
    the giant scallop Placopecten
    magellanicus](https://cdnsciencepub.com/doi/abs/10.1139/f95-074)
    (Stokesbury and Himmelman, 1995)
    -   Includes discussion of predation
-   Maine-specific
    -   [High Densities of Juvenile Sea Scallop (Placopecten
        magellanicus) on Banks and Ledges in the Central Gulf of
        Maine](https://doi.org/10.2983/035.029.0212) (Stokesbury et al.,
        2010) 
    -   [Estimating similarity in benthic communities over decades and
        in areas open and closed to fishing in the central Gulf of
        Maine, USA](https://www.int-res.com/abstracts/meps/v595/p15-26/)
        (Asci, Langton, and Stokesbury, 2018)
    -   [Development of a climate-niche model to evaluate spatiotemporal
        trends in Placopecten magellanicus distribution in the Gulf of
        Maine](https://journal.nafo.int/Portals/0/Vol50-2019/J50-Torre-721/J50-Torre-721.pdf)
        (Torre et al., 2019)
    -   [A Spatiotemporal Evaluation of Atlantic Sea Scallop Placopecten
        magellanicus Habitat in the Gulf of Maine Using a Bioclimate
        Envelope
        Model](https://afspubs.onlinelibrary.wiley.com/doi/full/10.1002/mcf2.10022)
        (Torre, Tanaka, and Chen, 2018)
-   Shell height and meat weight
    -   [Spatial and Temporal Variation in the Shell Height/Meat Weight
        Relationship of the Sea Scallop Placopecten magellanicus in the
        Georges Bank Fishery](https://doi.org/10.2983/035.028.0311)
        (Sarro and Stokesbury, 2009)

    -   [Variability in the relationship between sea scallop shell
        height and meat
        weight](https://academic.oup.com/icesjms/article/66/9/1972/726292)(Rothschild
        et al., 2009)

### Impacts of warming, fishing, and OA

-   [Effects of warming and fishing on Atlantic sea scallop (Placopecten
    magellanicus) size structure in the Mid-Atlantic rotationally closed
    areas](https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsad063/7125901?login=true)
    (Zang, 2023)
-   [Projected impacts of future climate change, ocean acidification,
    and management on the US Atlantic sea scallop
    fishery](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0203536)
    (Rheuban et al., 2018)
-   [Impacts of marine heat extremes on
    bivalves](https://doi.org/10.3389/fmars.2023.1159261) (Masanja et
    al., 2023)
-   [An Integrated Assessment Model for Helping the United States Sea
    Scallop Fishery Plan Ahead for Ocean Acidification and
    Warming](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0124145)
    (Cooley, 2015)
-   Experimental, not modeling: [Juvenile Atlantic sea scallop,
    Placopecten magellanicus, energetic response to increased carbon
    dioxide and temperature
    changes](https://journals.plos.org/climate/article?id=10.1371/journal.pclm.0000142)
    (Pousse et al., 2023)

### Dispersal, settlement, connectivity, spawning

-   [Impact of larval behaviors on dispersal and connectivity of sea
    scallop larvae over the northeast U.S.
    shelf](https://doi.org/10.1016/j.pocean.2021.102604) (Chen et al.,
    2022) 
-   [Spillover of sea scallops from rotational closures in the
    Mid-Atlantic
    Bight](https://academic.oup.com/icesjms/article/77/5/1992/5864487?login=true)
    (Hart et al., 2020)
-   [Identifying Spawning Events of the Sea Scallop Placopecten
    magellanicus on Georges Bank](https://doi.org/10.2983/035.033.0110)
    (Thompson, Inglis, and Stokesbury, 2014)
-   [Modeling dispersal of sea scallop larvae on Georges Bank: The
    influence of depth-distribution, planktonic duration and spawning
    seasonality](https://www.sciencedirect.com/science/article/pii/S0079661110001333?via%3Dihub)
    (Gilbert et al., 2010)
-   [Dispersal and settlement of sea scallop larvae spawned in the
    fishery closed areas on Georges
    Bank](https://academic.oup.com/icesjms/article/66/10/2155/679059?login=true)
    (Tian et al., 2009)
-   [Modeling the connectivity between sea scallop populations in the
    Middle Atlantic Bight and over Georges
    Bank](https://www.int-res.com/abstracts/meps/v380/p147-160/) (Tian
    et al., 2009)
-   [Fisheries Closed Areas Strengthen Scallop Larval Settlement and
    Connectivity Among Closed Areas and Across International Open
    Fishing Grounds: A Model
    Study](https://link.springer.com/article/10.1007/s00267-015-0526-9)
    (Davies et al., 2015)

### Natural mortality

-   [Natural mortality estimators for information-limited
    fisheries](https://onlinelibrary.wiley.com/doi/10.1111/faf.12027)
    (Kenchington, 2013)
-   [Estimating natural mortality for Atlantic Sea scallops (Placopecten
    magellenicus) using a size-based stock assessment
    model](https://www.sciencedirect.com/science/article/pii/S0165783622002004)
    (Hart and Chang, 2022)
-   [Natural mortality: Theory, estimation and application in fishery
    stock assessment
    models](https://www.sciencedirect.com/science/article/pii/S0165783623000310)
    (Hamel et al., 2023)

### Predation

-   [Effects of sea stars and crabs on sea scallop recruitment in the
    Mid-Atlantic
    Bight](https://www.int-res.com/articles/meps2006/306/m306p209.pdf)
    (Hart, 2006)
-   [Post-settlement predation by sea stars and crabs on the sea scallop
    in the Mid-Atlantic
    Bight](https://www.int-res.com/abstracts/meps/v468/p161-177/)
    (Shank, Hart, and Friedland, 2012)
-   [The Effect of Increasing Habitat Complexity on Bay Scallop Survival
    in the Presence of Different Decapod Crustacean
    Predators](https://link.springer.com/article/10.1007/s12237-014-9902-6)
    (Carroll et al., 2014)
-   [Effect of closed areas on populations of sea star Asterias spp. on
    Georges Bank](https://www.int-res.com/abstracts/meps/v347/p39-49/)
    (Marino, Juanes, and Stokesbury, 2007)
-   [Spatio-temporal variations of sea star Asterias spp. distributions
    between sea scallop Placopecten magellanicus beds on Georges
    Bank](https://www.int-res.com/abstracts/meps/v382/p59-68/) (Marino,
    Juanes, and Stokesbury, 2009)
-   [Incidental fishing mortality may be responsible for the death of
    ten billion juvenile sea scallops in the
    mid-Atlantic](https://www.int-res.com/abstracts/meps/v425/p167-173)
    (Stokesbury et al., 2011)
    -   [Mortality of sea scallops Placopecten magellanicus in the
        Mid-Atlantic Bight: Comment on Stokesbury et
        al.](https://www.int-res.com/abstracts/meps/v443/p293-297/)(Hart
        and Shank, 2011) - concluded it was actually crab predation

### Data

-   [Data & Visualization \|
    HabCam](https://habcam.whoi.edu/data-and-visualization/) 
-   <http://webserver.smast.umassd.edu/lab_stokesbury/ssib.html>
-   [Mid-Atlantic Ocean Data Portal scallop
    visualization](https://portal.midatlanticocean.org/visualize/#x=-75.08&y=37.71&z=8.258623674943928&logo=true&controls=true&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=485&basemap=ocean&themes%5Bids%5D%5B%5D=2&tab=data&legends=false&layers=true) 
-   [Google storage link to
    folders](https://console.cloud.google.com/storage/browser/_details/nmfs_odp_nefsc/PARR/EAD/HEB/27486/MA.zip;tab=live_object) 
-   [Northeast Ocean Data \| Data
    Explorer](https://www.northeastoceandata.org/data-explorer/)
-   [Data.gov Habitat Mapping Camera
    (HABCAM)](https://catalog.data.gov/dataset/habitat-mapping-camera-habcam)
-   [Data.gov Sea Scallop
    Survey](https://catalog.data.gov/dataset/sea-scallop-survey)
-   [Data.gov BOEM Benthic Habitat
    Assessment](https://catalog.data.gov/dataset/boem-benthic-habitat-assessment)
-   [Data.gov Benthic Habitat
    Dataset](https://catalog.data.gov/dataset/benthic-habitat-dataset)
-   [Data.gov population and biomass of United States sea scallop
    (Placopecten magellanicus) from an Atlantic Sea Scallop Integrated
    Assessment
    Model](https://catalog.data.gov/dataset/population-and-biomass-of-united-states-sea-scallop-placopecten-magellanicus-from-an-atlantic-s)
-   [NOAA Fisheries Habitat Mapping Camera (HABCAM) \|
    InPort](https://www.fisheries.noaa.gov/inport/item/27598)
-   [NOAA Fisheries Sea Scallop Survey \|
    InPort](https://www.fisheries.noaa.gov/inport/item/22564) 

### Survey metadata, overviews, and methodology

-   [Methods for Image-based Surveys of Benthic Macroinvertebrates and
    Their Habitat Exemplified by the Drop Camera Survey for the Atlantic
    Sea
    Scallop](https://www.jove.com/t/57493/methods-for-image-based-surveys-benthic-macroinvertebrates-their)
    (Bethoney and Stokesbury, 2018)
-   [A Cooperative High Precision Dredge Survey to Assess the
    Mid-Atlantic Sea Scallop Resource Area in 2019 and 2020: Final
    Report](https://scholarworks.wm.edu/reports/2781/) (Roman and
    Rudders, 2022)
-   [SMAST Sea scallop (Placopecten magellanicus) drop camera survey
    from 1999 to
    2014](http://www.repstraus.com/wp-content/uploads/2015/03/SMAST-drop-cam-survey-1999-2014-Stokesbury.pdf)
    (Stokesbury et al, 2015)
-   [Average (2003-2012) Presence/Abundance from SMAST
    Survey](https://easterndivision.s3.amazonaws.com/Marine/MooreGrant/AveragePresenceAbundanceSMAST.pdf)
-   [Results from the 2006 Maine sea scallop
    survey](https://cobscook.org/assets/files/2006%20scallop%20survey%20final%20report.pdf)

### Maps and figures (of shellfish strata, closed areas, etc)

-   [Figs. 1 and
    2](https://www.int-res.com/articles/meps2007/347/m347p039.pdf)
-   [Page
    9](https://www.northeastoceandata.org/wp-content/uploads/2018/03/ID310_Draft_Product_1-NEFSC_Dredge.pdf)
-   [Fig.
    1](https://www.sciencedirect.com/science/article/pii/S0165783622002004#bib7)
    (full-size
    [here](https://ars.els-cdn.com/content/image/1-s2.0-S0165783622002004-gr1_lrg.jpg))
