---
title: 'June 12'
date: '2023-06-12'
categories: ['Week 2', 'Data exploration', 'Reading']
description: 'My activities for the day.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

### Reading EDM papers
This morning...

### Python Practice
This afternoon...

## Data exploration

Load packages
```{r}
library(ggplot2)
library(dplyr)

```

Looking at 22564_UNION_FSCS_SVCAT (one out of five .csv files in the folder shared by Dr. Deyle)
```{r}
#read data
svcat <- read.csv("~/Downloads/lab_notebook/data/22564_UNION_FSCS_SVCAT.csv")

#view the first six rows of data
head(svcat)

#different overviews of the data
summary(svcat)
glimpse(svcat)
```

```{r}
#filter to only species of interest - takes it from 94632 obs to 21425 vars
scallops <- svcat %>% 
  filter(SCIENTIFIC_NAME=="Placopecten magellanicus (sea scallop)" | 
           SCIENTIFIC_NAME =="Placopecten magellanicus (sea scallop clapper)")

scallops <- scallops %>% 
  mutate(name = as.factor(SCIENTIFIC_NAME),
         cruise6 = as.factor(CRUISE6),
         cruise = as.factor(CRUISE),
         sex = as.factor(CATCHSEX),
         .keep = "unused")

summary(scallops)
```

```{r echo=FALSE}
rm(svcat)
```

```{r}

```

