---
title: 'June 9'
date: '2023-06-09'
categories: ['Week 1', 'Events', 'Reading']
description: 'My activities for the day.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

## Python Practice
This morning I worked through the [Introduction to Python](https://programming-workshops.readthedocs.io/en/latest/workshops/03_python/index.html) section of the BRITE Python programming workshop. 

## UROP BBQ
At noon we had the Summer Kick-Off BBQ sponsored by the BU Undergraduate Research Opportunities Program (UROP). I had the chance to talk with some students from BU who are doing chemistry research over the summer. It was interesting to hear about their research, especially in areas (related to inorganic chemistry) that I am less familiar with.

## EDM & Meeting
In the afternoon I continued to work on the Intro to EDM page. I finished the simplex projection and S-map sections and started on the CCM section. I also had a productive Zoom meeting with Dr. Deyle where we discussed my progress thus far and directions for future work. We focused somewhat on the potential spatial aspect of the project, and he provided examples of spatial EDM papers as well as a list of R packages that are useful for spatial analysis.