---
title: 'Week 3'
date: '2023-06-23'
categories: ['Week 3', 'Reading', 'Data exploration']
description: 'My activities for the week'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

## Monday, June 19

Since today was a holiday, I didn't come into the lab and do "work" in the form of direct project tasks or data analysis. However, I spent many hours reading the book *Fisheries Ecosystem Dynamics* ([Fogarty and Collie, 2020](https://academic.oup.com/book/41043)). I have not yet taken any classes directly focused on ecology, population dynamics, or fisheries, and I believe that I will be able to produce more meaningful and accurate results for my BRITE project if I have a higher level of background knowledge. I like to take a lot of time and work through the calculations and derivations presented in the book myself, so I really understand both the biological significance and mathematical properties of important equations. Today I got through Chapter 1: Introduction (Sections 1.1-1.4), Chapter 2: Density-Independent Population Growth (Sections 2.1-2.4), and started on Chapter 3: Density-Dependent Population Growth (Section 3.1). I hope to continue to work through at least a few sections of the book each day, at least until I get to Chapter 14: Empirical Dynamic Modeling.

## Tuesday, June 20

I spent most of today working on a project proposal document. Having a concrete outline will be useful for me personally to provide direction and structure for moving forward with the project, but it will also be valuable to have a document that can be shared with others who could provide meaningful input. I conducted a fairly comprehensive literature review for the Relevance & Background and Summary of Selected Literature sections, and added many of those papers to the EDM and Scallop links pages on this website. I also started Section 3.2 in *Fisheries Ecosystem Dynamics,* "Compensation in simple population models", which included subsections on continuous-time models (3.2.1) and multiple equilibria (3.2.2).

## Wednesday, June 21

Today I finalized the Proposed Methods and Hypotheses sections of my project proposal and shared the document with Dr. Deyle and Dr. Kaufman. I also updated and reformatted several pages on my lab notebook so it can be useful as a resource/literature repository in addition to documenting my progress. In the afternoon, I attended the monthly Zoom working session for the American Fisheries Society Climate Ambassador Program, a 2-year science communication program for fisheries scientists. Each month, we have a training session covering a different topic (e.g., May's topic was dealing with challenging audiences), with a working session the following week to practice implementing what we've learned. The program has definitely made me more skilled at creating effective posters and presentations about my research, as I will need to do for the BRITE REU symposium in August. After the training session, I started working through some of the R code provided as supplementary material to EDM papers, with the goal of building skill and confidence working with the rEDM and multispatialCCM packages. I also read subsection 3.3.3 in *Fisheries Ecosystem Dynamics,* which focused on discrete-time density-dependent models and included a sub-subsection titled "Complex Dynamics" that was highly relevant to EDM.

## Thursday, June 22

Today, I...

**1. Attended the BRITE R programming workshop.** I was already relatively comfortable working in R (certainly compared to working in Python), but it was still valuable to see alternative ways to accomplish a given task. The workshop also introduced me to Bioconductor packages, which are used for "statistical analysis and comprehension of high-throughput genomic data".

**2. Worked through the [rEDM vignette](https://cran.r-project.org/web/packages/rEDM/vignettes/rEDM-tutorial.pdf)**. I tried to reproduce all of the R code in the vignette and as I did so, I wrote up a list of questions to ask Dr. Deyle. In particular, I would like to know more about how to specify function inputs like the sizes of the training and prediction libraries for Simplex, S-map, and CCM; the method used to produce surrogate data for testing statistical significance, and different approaches to normalizing data before analysis.

**3. Tried to debug code.** After finishing the rEDM vignette, I tried to reproduce the code provided as supplementary material to the paper "Ecosystem-based forecasts of recruitment in two menhaden species"([Deyle et al., 2018](https://doi.org/10.1111/faf.12287)). Unlike the vignette, many of the functions produced errors when called, so I tried to identify the cause of the error and potential alternative solutions. However, the error messages were somewhat hard to interpret because the error tracebacks often referred to the underlying C++ code. For example, RStudio would produce an error message that an integer had been provided where a string was expected, but to some function called by the rEDM package, not to a function that was in my R script that I could edit.

## Friday, June 23

Today, I...

**1. Worked through EDM code.** I continued to try and debug the code provided with the menhaden paper, and also worked through the code accompanying [Chang et al., (2017)](https://link.springer.com/article/10.1007/s11284-017-1469-9). I was comparatively more successful at debugging Chang et al., and I managed to figure out alternative ways to create the figures in the paper.

**2. Read papers applying EDM to fisheries.** I especially focused on the methods sections, and took notes on steps in their analysis that would be useful perform on the scallop data (see Intro to EDM page). For example, I identified many different ways that authors have chosen to assess the statistical significance of EDM results.

**3. Tested out NOAA R packages in the SCC.** I installed and explored three different packages to see if they would be useful for my project: [NEFSC-Spatial](https://nefsc.github.io/NEFSC-Spatial/index.html) (has shellfish strata), [stocksmart](https://noaa-edab.github.io/stocksmart/), and [ecodata](https://noaa-edab.github.io/ecodata/landing_page%20https://noaa-edab.github.io/ecodata/). As the packages come with fairly large data files, I leveraged the power of the SCC when testing their functionality. My conclusion is that the data included in the packages has relatively coarse resolution and will likely not be directly useful for my EDM scallop project, but that they are excellent for data visualization. The plots I can produce with the NOAA packages might be good for providing context about the geographical, biological, and economic context of my project.

```{r, eval=FALSE}
library(tidyverse)

library(ecodata)
comdat #aggregated commercial fishing data (landings, value, etc.)
str(comdat)
levels(comdat$EPU)

varFactors <- as.factor(comdat$Var)
levels(varFactors)

library(stocksmart)
hab<- habitat_occupancy
get_available_ts(itis = 79718, jurisdiction = "NEFMC") #ITIS = 79718 refers to the Integrated Taxonomic Information System number for the sea scallop.
plot_ts(itis = 79718, facetplot = T) #plots time series
get_latest_full_assessment(itis = 79718)
scal<-get_latest_metrics(itis = 79718)

scallopData<- stockAssessmentData %>% 
  filter(ITIS==79718)
```
