---
title: 'Week 5'
date: '2023-07-04'
categories: ['Week 5']
description: 'My activities for the week'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

## Monday, July 3 (+ preceding weekend)

1. I spent most of the day working with the scallop data that Dr. Hart emailed me on Friday. As she requested, I created an R script that turns the data file she gave me into two data frames with lists of 3 or more consecutive stations that have been labeled as star/crab samples not taken. I also manually read the catch comment for each station to evaluate the possibility that crabs/starfish might have been sampled at that station and the catch photo needs to be checked.
2. I worked through the SCC+Bash BRITE Workshop materials that Michael emailed us so I will be prepared for the workshop on Thursday. I learned a great deal of new syntax and practiced creating and running basic bash scripts on the SCC.

## Tuesday, July 4

Although today was technically a holiday, today I...
1. Worked through athlete survey/sensor repository Dr. Deyle shared with me
2. Based on clarification provided by Dr. Hart, I created a list of the stations with a comment mentioning "stars and crabs" (affirmative). I also made an updated version of the csv file I sent previously that lists the first stations in runs of 3+ consecutive stations with "starsample = FALSE". The new version excludes five such runs that would not exist if the stations with a "stars and crabs" comment were all changed to "starsample = TRUE".

## Wednesday, July 5

1. Maine data: grid overlays
2. Function to do EDM on Maine-formatted input file

## Thursday, July 6

1. BRITE Programming Workshop: Bash/Linux
2. Working on identifying nearest neighbors

## Friday, July 7

1. Writing functions to bootstrap samples
2. Meeting with Dr. Deyle, Josue, and Dr. Suchi Gopal