---
title: 'Week 1 in Words'
date: '2023-06-09'
categories: ['Week 1', 'Events', 'Reading']
description: 'My first week on the job! Lots of getting organized, reading papers, and learning/refreshing my knowledge of Git, GitHub, R Markdown, Python, and Quarto. We also had our first programming workshop and attended the 16th Annual Student-Organized Bioinformatics Symposium.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# Tuesday, June 6th

## Papers
I spent much of today reading the papers that Dr. Deyle provided related to EDM and quantitative fisheries. The EDM papers included applications of the approach to specific case studies, as well as the mathematical background. For example, [@sugihara_detecting_2012] is the foundational paper describing the use of EDM to detect causality through convergent cross-mapping (CCM).

I also familiarized myself with recent modeling studies related to the Atlantic sea scallop fishery. The economic value of the scallop fishery and the availability of high-quality time series data make scallops a good choice for meaningful applied data science. There have been various models created to estimate biomass (stock assessments), estimate natural mortality, and to develop an Integrated Assessment Model to inform fishery management under changing oceanographic conditions. However, these models depend on assumptions (especially about stock-recruitment relationships) that may not be justified. EDM could potentially provide new insights into the factors that impact scallop abundance without needing to make such assumption.

There are also many interesting spatial dynamics to consider, particularly related to the rotational management plans implemented by the New England Fishery Management Council. Another potential area of investigation relates to new research by Pousse et al., [-@pousse_juvenile_2023] indicating that ocean acidification depresses the growth of juvenile Atlantic sea scallops. This research highlights the need for accurate forecasting of scallop populations under projected acidification conditions in order to ensure the continued prosperity of the fishery.

## Building this notebook

### Git and GitHub
Unfortunately, I had to spend several hours today wrangling with Git and GitHub in order to create the new repository for this notebook and successfully connect it to GitHub. The main issues were related to inconsistent authentication protocols (HTTPS vs. ssh) between my GitHub account, GitHub CLI, and local repo. Eventually, I resolved the issues and successfully link the local and remote directories and deploy this notebook as a GitHub pages site associated with the repository.

### Quarto and Markdown
It has been several years since I last worked in Markdown, and I reviewed the basic syntax: headers, italics, bullet points, inserting links, etc. My previous experience using Markdown syntax was in R Markdown, but for this lab notebook I decided to learn Quarto. [Quarto](https://quarto.org/) is an "open-source scientific and technical publishing system" that is used by academics to create static and dynamic documents, personal websites, CVs, books, and other media. Called the next generation of R Markdown, knowing how to use Quarto will be a valuable skill for this REU project as well as future research endeavors.

## Goals/Future Work
1. Finish reading the all of the quantitative fisheries papers that Dr. Deyle provided
2. Create a blog page (blog = lab notebook website) to collect and organize my list of relevant papers
3. EDM
    a. Create an "Intro to EDM" blog page where I can summarize my understanding of EDM and associated analytical techniques. I am not sure that my grasp of the theory behind EDM is solid enough to accurately apply it to complex systems or to explore new conceptual areas, and I think that writing such a page (much like teaching a concept to someone else) will help me identify and resolve gaps in my understanding.
    b. Solidify my understanding of the different ways that EDM can incorporate spatial data. I plan to re-read some of the key spatial EDM papers to review the theory and the methods they used, as during my initial read I mostly focused on the introduction, results, and discussion/conclusions. I primarily want to feel more confident in my ability to determine which approach(es) would be most suitable for a given data set.
4. Begin looking at the scallop data

# Wednesday, June 7

Today was spent at the 16th Annual BU Bioinformatics Student-Organized Symposium. I found the entire symposium very interesting and filled up five pages of my notebook with concepts, techniques, and papers mentioned in the presentations that I wanted to save to look up on my own later. Here are some examples of things I recorded that were novel to me or that particularly caught my interest:

*   The phyllosphere
*   Flux Balance Analysis
*   MacArthur's consumer-resource model
*   Genomic epidemiology

My favorite part of the symposium was Dr. Alan Pacheco's presentation on "Mapping Interaction Networks in Plant Microbiomes", although I also enjoyed PhD candidate Helen Scott's lightning talk on "Charting Carbon Use Efficiency in Ocean Microbiomes".

Cool papers mentioned or cited at the conference include:

*    Microbiology of the phyllosphere ([Lindow and Brandl, 2003](https://doi.org/10.1128%2FAEM.69.4.1875-1883.2003))
*    Mapping phyllosphere microbiota interactions in planta to establish genotype-phenotype relationships ([Schäfer et al., 2022](https://doi.org/10.1038/s41564-022-01132-w))
*    A protocol for generating a high-quality genome-scale metabolic reconstruction ([Thiele and Palsson, 2010](https://doi.org/10.1038%2Fnprot.2009.203))
*    What is flux balance analysis? ([Orth et al., 2010](https://doi.org/10.1038%2Fnbt.1614))
*    Fast automated reconstruction of genome-scale metabolic models for microbial species and communities ([Machado et al., 2018](https://doi.org/10.1093/nar/gky537))

# Thursday, June 8

## BRITE REU trainings & workshops
This morning we had our first programming workshop as part of the BRITE REU program, led by Michael Silverstein. We learned how to access the SSC and set up interactive sessions in Jupyter Notebook and RStudio.

We then had an ethics training alongside students from other REU programs at Boston University. I have had many similar ethics trainings before and am always cognizant of the need to avoid scientific misconduct, but it was interesting to hear the speaker describe several high-profile misconduct cases with which I was unfamiliar (like [Mark Spector](https://www.thecrimson.com/article/1981/10/3/cornell-researcher-quits-over-false-cancer/)).

## EDM
I spent this afternoon reading and re-reading papers that Dr. Deyle provided related to EDM. I also read more about the basics of dynamical systems theory, which underpins EDM (and indeed, much of modern science). I started working on an [Intro to EDM](https://rmk118.github.io/lab_notebook/Resources/EDM.html) page for this site and found that attempting to articulate the concepts in my own words was tremendously helpful in solidifying my understanding of the concepts.

# Friday, June 9

## Python Practice
This morning I worked through the [Introduction to Python](https://programming-workshops.readthedocs.io/en/latest/workshops/03_python/index.html) section of the BRITE Python programming workshop. 

## UROP BBQ
At noon we had the Summer Kick-Off BBQ sponsored by the BU Undergraduate Research Opportunities Program (UROP). I had the chance to talk with some students from BU who are doing chemistry research over the summer. It was interesting to hear about their research, especially in areas (related to inorganic chemistry) that I am less familiar with.

## EDM & Meeting
In the afternoon I continued to work on the Intro to EDM page. I finished the simplex projection and S-map sections and started on the CCM section. I also had a productive Zoom meeting with Dr. Deyle where we discussed my progress thus far and directions for future work. We focused somewhat on the potential spatial aspect of the project, and he provided examples of spatial EDM papers as well as a list of R packages that are useful for spatial analysis.

# References